version: '3'
services:
    backend:
        build: ./app
        environment:
            - NODE_ENV=development
            - FOO=bar
        volumes:
            - ./app:/var/www:rw
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        ports:
            - 3001:3001
        links:
            - mongodb
        depends_on:
            - mongodb
    frontend:
        build: ./client
        environment:
            - NODE_ENV=development
            - FOO=bar
        volumes:
            - ./client:/var/www:rw
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        ports:
            - 3000:3000
        links:
            - backend
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
